services:
  kong-database:
    image: postgres:15
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-data:/var/lib/postgresql/data

  kong-migrations:
    image: kong:3.7
    container_name: kong-migrations
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
    entrypoint: ["/bin/sh", "-c", "kong migrations bootstrap && exit"]

  kong:
    image: kong:3.7
    container_name: kong-gateway
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "443:8002"
      - "8003:8003"
      - "8004:8004"
      - "8443:8443"
      - "8444:8444"

    volumes:
      - kong-config:/etc/kong
    extra_hosts:
      - host.docker.internal:172.17.0.1

volumes:
  kong-data:
  kong-config:
